---
- hosts: webservers
  become: true
  become_user: root
  vars_prompt:
   - name: docker_password
     prompt: enter docker pwd for the registry
  tasks:
  - name: Install docker
    vars:
      ansible_python_interpreter: /usr/bin/python
    yum: name=docker state=present
  - name: start docker
    service: name=docker state=started
  - name: Install docker python modules
    pip:
      name:
      - docker
  - name: Docker test
    docker_image: name=nginx source=pull
  - name: docker login
    docker_login:
       registry_url: https://index.docker.io/v1/
       username: devopstrainer
       password: "{{docker_password}}"
  - name: run the docker image
    docker_container:
       name: addbook
       image: "{DOCKER_IMAGE}"
       published_ports: 80
